version: '3'

services:
  alliot-app:
    image: johnpapa/angular-cli
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./frontend/:/home/node/app
    ports:
      - 4200:4200
    command: "npm start"
  alliot-server:
    image: node:10.13.0
    user: "node"
    working_dir: /home/node/server
    volumes:
      - ./backend/:/home/node/server
    ports:
      - 3000:3000
    command: "npm start"

